[tool.poetry]
name = "geolib"
version = "0.1.0"
description = ""
authors = ["Maarten Pronk <maarten.pronk@deltares.nl>", "Deltares"]
license = "LGPLv3" 
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
jsonschema = "^3.2"
mypy = "^0.761.0"
sphinx = "^2.4"
recommonmark = "^0.6.0"
pydantic = {extras = ["all"], version = "^1.4"}
hypothesis-jsonschema = "^0.11.1"
flake8 = "^3.7.9"
black = "^19.10b0"
devtools = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tox]
isolated_build = true
envlist = "py37, py38"

[mypy]
python_version = 3.7

[pytest]
testpaths = "tests"

[isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=88
