[tool.poetry]
name = "geolib"
version = "0.1.1"
description = ""
authors = ["Maarten Pronk <maarten.pronk@deltares.nl>", "Deltares"]
license = "LGPLv3" 
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
jsonschema = "^3.2"
pydantic = {extras = ["all"], version = "^1.4"}
python-dotenv = "^0.12.0"
zipp = "^3.1.0"
fastapi = {version = "^0.58.1", optional = true}
uvicorn = {version = "^0.11.5", optional = true}
requests = "^2.24.0"
jinja2 = "^2.11.2"

[tool.poetry.dev-dependencies]
teamcity-messages = "^1.27"
flake8 = "^3.7.9"
black = "^19.10b0"
devtools = "^0.5.1"
coverage = "^5.0.4"
pytest = "^5.4.1"
teamcity_messages = "^1.27"
pytest-cov = "^2.8.1"
rst2pdf = "^0.96"
hypothesis-jsonschema = "^0.11.1"
mypy = "^0.761.0"
sphinx = "^2.4"
recommonmark = "^0.6.0"
releases = "^1.6.3"

[tool.poetry.extras]
server = ["fastapi", "uvicorn"]

[tool.poetry.scripts]
geolib_server = "geolib.service.main:app"

[tool.black]
line-length = 90
target-version = ['py37']
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tox]
isolated_build = true
envlist = "py37, py38"

[pytest]
testpaths = "tests"

[isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=90

